-- poco definition

-- Drop table

-- DROP TABLE poco;

CREATE TABLE joclamar.poco (
	field1 numeric NOT NULL,
	field2 numeric NULL,
	field3 numeric NULL,
	field4 numeric NULL,
	field5 numeric NULL,
	field6 numeric NULL,
	field7 numeric NULL,
	field8 numeric NULL,
	field9 numeric NULL,
	field10 numeric NULL,
	field11 numeric NULL,
	field12 numeric NULL,
	field13 numeric NULL,
	field14 numeric NULL,
	field15 text NULL,
	field16 numeric NULL,
	field17 numeric NULL,
	field18 numeric NULL,
	field19 numeric NULL,
	field20 text NULL,
	field21 numeric NULL,
	field22 numeric NULL,
	field23 numeric NULL,
	field24 text NULL,
	field25 text NULL,
	field26 text NULL,
	field27 text NULL,
	field28 numeric NULL,
	field29 numeric NULL,
	field30 numeric NULL,
	field31 numeric NULL,
	field32 text NULL,
	field33 numeric NULL,
	field34 text NULL,
	field35 text NULL,
	field36 numeric NULL,
	field37 numeric NULL,
	field38 numeric NULL,
	field39 numeric NULL,
	field40 numeric NULL,
	field41 numeric NULL,
	field42 numeric NULL,
	field43 numeric NULL,
	field44 numeric NULL,
	field45 numeric NULL,
	field46 numeric NULL,
	field47 numeric NULL,
	field48 numeric NULL,
	field49 text NULL,
	field50 numeric NULL,
	field51 numeric NULL,
	field52 numeric NULL,
	field53 numeric NULL,
	field54 numeric NULL,
	field55 numeric NULL,
	field56 numeric NULL,
	field57 uuid NULL,
	field58 timestamp NULL,
	field59 numeric NULL,
	field60 uuid NULL,
	field61 uuid NULL,
	field62 numeric NULL,
	field63 numeric NULL,
	field64 uuid NULL,
	field65 text NULL,
	field66 text NULL,
	field67 timestamp NULL,
	field68 numeric NULL,
	field69 numeric NULL,
	field70 timestamp NULL
);